### ISSUE TITLE
can blend models (different kind) be explained by shap?

### ISSUE THREAD

**Issue by XiangBu** [srmatth/mshap#1]
As show in the following pic, I's like to blend lightgbt and lda to balance the AUC and recall, It turns out the result is good. However it seems blend models cannot be explained by shap. Is mshap  provide any function to solve this? THANKS A LOT!

![image](https://user-images.githubusercontent.com/46986985/144813192-064ae0a5-f845-465a-9032-eaf62bbd1e73.png)

**Comment by srmatth** [comment]
Hi! Great question, and I guess the answer depends on how you are blending the model. Are you taking an average of the two models or is there a different method that you are using to blend the two selected models?

**Comment by XiangBu** [comment]
> Hi! Great question, and I guess the answer depends on how you are blending the model. Are you taking an average of the two models or is there a different method that you are using to blend the two selected models?

I just using voting classifier or stacking classifier

**Comment by srmatth** [comment]
If you are just doing something like that, I would presume you could find the information in this github issue (from the original shap github repo) helpful:

https://github.com/slundberg/shap/issues/112

Let me know if that answers your question.
